import{useEffect,useMemo,useState}from'react';import type{IChartApi,ISeriesApi,UTCTimestamp}from'lightweight-charts';import type{RiskReward}from'@trade/shared';import{calculateRiskReward}from'@trade/domain';

type DragKind='entry'|'stop'|'target'|'startTime'|'endTime';
export default function RiskRewardOverlay({chart,series,host,items,selectedId,onSelect,onUpdate}:{chart:IChartApi|null;series:ISeriesApi<'Candlestick'>|null;host:HTMLDivElement|null;items:RiskReward[];selectedId:number|null;onSelect:(r:RiskReward)=>void;onUpdate:(id:number,p:Partial<RiskReward>)=>void}){
 const[version,setVersion]=useState(0);const[draft,setDraft]=useState<RiskReward|null>(null);const[drag,setDrag]=useState<{kind:DragKind;item:RiskReward}|null>(null);
 useEffect(()=>{if(!chart)return;const cb=()=>setVersion(v=>v+1);chart.timeScale().subscribeVisibleTimeRangeChange(cb);const ro=host?new ResizeObserver(cb):null;if(host)ro?.observe(host);return()=>{chart.timeScale().unsubscribeVisibleTimeRangeChange(cb);ro?.disconnect()}},[chart,host]);
 useEffect(()=>{if(!drag||!series||!chart||!host)return;const move=(e:PointerEvent)=>{const rect=host.getBoundingClientRect();let next={...(draft||drag.item)};if(drag.kind==='entry'||drag.kind==='stop'||drag.kind==='target'){const p=series.coordinateToPrice(e.clientY-rect.top);if(p&&p>0)next={...next,[drag.kind]:p};}else{const t=chart.timeScale().coordinateToTime(e.clientX-rect.left);if(typeof t==='number')next={...next,[drag.kind]:t};}setDraft(next);};const up=()=>{if(draft)onUpdate(draft.id,{entry:draft.entry,stop:draft.stop,target:draft.target,startTime:draft.startTime,endTime:draft.endTime,direction:draft.target>=draft.entry?'long':'short'});setDrag(null);setDraft(null)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[drag,draft,series,chart,host,onUpdate]);
 const display=useMemo(()=>items.map(i=>draft?.id===i.id?draft:i),[items,draft,version]);if(!chart||!series||!host)return null;
 return <svg className="chart-overlay" width={host.clientWidth} height={host.clientHeight}>{display.map(r=>{const x1=chart.timeScale().timeToCoordinate(r.startTime as UTCTimestamp);const x2=chart.timeScale().timeToCoordinate(r.endTime as UTCTimestamp);const ye=series.priceToCoordinate(r.entry),ys=series.priceToCoordinate(r.stop),yt=series.priceToCoordinate(r.target);if(x1===null||x2===null||ye===null||ys===null||yt===null)return null;const left=Math.min(x1,x2),right=Math.max(x1,x2),w=Math.max(30,right-left);const rewardTop=Math.min(ye,yt),riskTop=Math.min(ye,ys);const rr=calculateRiskReward(r.entry,r.stop,r.target);const selected=selectedId===r.id;return <g className="rr-object" key={r.id} onPointerDown={()=>onSelect(r)}><rect className="rr-reward" x={left} y={rewardTop} width={w} height={Math.max(1,Math.abs(yt-ye))} rx="2"/><rect className="rr-risk" x={left} y={riskTop} width={w} height={Math.max(1,Math.abs(ys-ye))} rx="2"/><line className="rr-entry" x1={left} x2={left+w} y1={ye} y2={ye}/><text x={left+8} y={rewardTop+15}>R:R {rr.ratio.toFixed(2)} · {r.direction.toUpperCase()}</text>{selected&&<><circle className="rr-handle" cx={left+w} cy={yt} r="6" onPointerDown={e=>{e.stopPropagation();setDrag({kind:'target',item:r})}}/><circle className="rr-handle" cx={left+w} cy={ye} r="6" onPointerDown={e=>{e.stopPropagation();setDrag({kind:'entry',item:r})}}/><circle className="rr-handle" cx={left+w} cy={ys} r="6" onPointerDown={e=>{e.stopPropagation();setDrag({kind:'stop',item:r})}}/><circle className="rr-handle time" cx={left} cy={ye} r="5" onPointerDown={e=>{e.stopPropagation();setDrag({kind:'startTime',item:r})}}/><circle className="rr-handle time" cx={left+w} cy={ye} r="5" onPointerDown={e=>{e.stopPropagation();setDrag({kind:'endTime',item:r})}}/></>}</g>})}</svg>
}
