import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Camera, ClipboardPaste, Image as ImageIcon, RefreshCw, Trash2, UploadCloud, X } from 'lucide-react';
import type { AccountPublic } from '@trade/shared';
import { api, json, money, num } from '../api';
import { useI18n } from '../i18n';
import { usePreferences } from '../preferences';
import { createJournalChartSnapshots, type SnapshotInterval, type SnapshotTrade } from '../journalSnapshots';

type JournalRow = SnapshotTrade & {
  trigger_price:number|null; point_type:number|null; price_level:number|null; rr:number|null; style:number|null; note:string|null; chart_path:string|null;
  exchange:string|null; pnl:number|null; fees:number|null; setup:string|null; tags_json:string|null; execution_quality:string|null; image_count?:number|null;
};

type JournalImage={id:number;journal_order_id:number;kind:'before'|'entry'|'management'|'exit'|'other';path:string;original_name:string|null;mime:string;size_bytes:number;created_at:string};
type Breakdown={name:string;trades:number;wins:number;losses:number;net:number};
type JournalPageResponse={
  rows:JournalRow[]; total:number; page:number; pageSize:number; totalPages:number;
  summary:{trades:number;winrate:number;net:number;avg:number;pf:number|null;avgWin:number;avgLoss:number};
  breakdowns:{style:Breakdown[];account:Breakdown[];side:Breakdown[];point:Breakdown[];setup:Breakdown[]};
};
type SortMode='newest'|'oldest'|'best_r'|'worst_r'|'highest_pnl';
type FilterState={account:number;symbol:string;side:string;style:string;status:string;pointType:string;dateFrom:string;dateTo:string;sort:SortMode;tab:'trades'|'analytics';page:number};

const shotKinds=[['before','Before'],['entry','Entry'],['management','Management'],['exit','Exit'],['other','Other']] as const;
const kindLabel=(kind:string)=>shotKinds.find(x=>x[0]===kind)?.[1]||kind;
const styleMap:Record<number,string>={0:'—',1:'Breakout',2:'LP',3:'Rebound'};
const statusMap:Record<number,string>={0:'New',1:'Filled',2:'Cancelled'};
const pointTypeMap:Record<number,string>={10:'Stop Limit · ATR SL',11:'Stop Limit · Technical SL',20:'Limit · ATR SL',21:'Limit · Technical SL',30:'Market · ATR SL',31:'Market · Technical SL'};
const rrOptions=[-1,0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5];
const FILTER_KEY='trade.journal.filters.v2';
const defaultFilters:FilterState={account:0,symbol:'',side:'',style:'',status:'',pointType:'',dateFrom:'',dateTo:'',sort:'newest',tab:'trades',page:1};

const parseTags=(value:string|null)=>{try{const x=JSON.parse(value||'[]');return Array.isArray(x)?x.map(String):[];}catch{return[];}};
const fileToBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error||new Error('Could not read image'));reader.onload=()=>{const value=String(reader.result||'');resolve(value.includes(',')?value.slice(value.indexOf(',')+1):value);};reader.readAsDataURL(file);});
const readStoredFilters=():Partial<FilterState>=>{try{return JSON.parse(localStorage.getItem(FILTER_KEY)||'{}')||{};}catch{return{};}};
const autoSnapshotLabel=(name:string|null)=>{const n=(name||'').toLowerCase();if(n.startsWith('auto-chart-5m-'))return'5m';if(n.startsWith('auto-chart-1h-'))return'1H';if(n.startsWith('auto-chart-1d-'))return'1D';return null;};
const pageButtons=(page:number,total:number)=>{const out:number[]=[];const start=Math.max(1,Math.min(page-2,total-4));const end=Math.min(total,start+4);for(let i=start;i<=end;i++)out.push(i);return out;};

export default function JournalPage(){
  const qc=useQueryClient();
  const {t,language}=useI18n();
  const {preferences}=usePreferences();
  const initial=useMemo(()=>{const saved=readStoredFilters();return (preferences.journal.rememberFilters?{...defaultFilters,...saved,page:preferences.journal.rememberPage?Number(saved.page||1):1}:defaultFilters) as FilterState;},[]);
  const[filters,setFilters]=useState<FilterState>(initial);
  const[selected,setSelected]=useState<JournalRow|null>(null);
  const[image,setImage]=useState<string|null>(null);
  const[shotKind,setShotKind]=useState<JournalImage['kind']>('before');
  const[dropActive,setDropActive]=useState(false);
  const fileInput=useRef<HTMLInputElement|null>(null);

  const config=useQuery<{accounts:AccountPublic[]}>({queryKey:['config'],queryFn:()=>api('/api/config')});
  const queryString=useMemo(()=>{const p=new URLSearchParams({page:String(filters.page),pageSize:String(preferences.journal.pageSize),sort:filters.sort});if(filters.account)p.set('accountId',String(filters.account));if(filters.symbol)p.set('symbol',filters.symbol);if(filters.side)p.set('side',filters.side);if(filters.style!=='')p.set('style',filters.style);if(filters.status!=='')p.set('status',filters.status);if(filters.pointType!=='')p.set('pointType',filters.pointType);if(filters.dateFrom)p.set('dateFrom',filters.dateFrom);if(filters.dateTo)p.set('dateTo',filters.dateTo);return p.toString();},[filters,preferences.journal.pageSize]);
  const q=useQuery<JournalPageResponse>({queryKey:['journal-page',queryString],queryFn:()=>api(`/api/journal/page?${queryString}`),refetchInterval:5000});
  const images=useQuery<JournalImage[]>({queryKey:['journal-images',selected?.id],queryFn:()=>api(`/api/journal/${selected!.id}/images`),enabled:Boolean(selected)});

  const update=useMutation({mutationFn:({id,patch}:{id:number;patch:any})=>api<JournalRow>(`/api/journal/${id}`,json('PATCH',patch)),onSuccess:(row)=>{setSelected(row);void qc.invalidateQueries({queryKey:['journal-page']});}});
  const uploadOne=async(id:number,file:File,kind:JournalImage['kind'])=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Only PNG, JPEG and WEBP images are allowed');if(file.size>8*1024*1024)throw new Error(`${file.name} is larger than 8 MB`);const dataBase64=await fileToBase64(file);return api(`/api/journal/${id}/images`,json('POST',{kind,name:file.name,mime:file.type,dataBase64}));};
  const uploadImages=useMutation({mutationFn:async({files,kind}:{files:File[];kind:JournalImage['kind']})=>{if(!selected)throw new Error('Select a journal trade first');for(const file of files)await uploadOne(selected.id,file,kind);},onSuccess:()=>{void qc.invalidateQueries({queryKey:['journal-images',selected?.id]});void qc.invalidateQueries({queryKey:['journal-page']});}});
  const deleteImage=useMutation({mutationFn:(id:number)=>api(`/api/journal/images/${id}`,{method:'DELETE'}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['journal-images',selected?.id]});void qc.invalidateQueries({queryKey:['journal-page']});}});
  const syncJournal=useMutation({mutationFn:()=>api('/api/journal/sync',{method:'POST'}),onSuccess:()=>void qc.invalidateQueries({queryKey:['journal-page']})});
  const generateSnapshots=useMutation({mutationFn:async()=>{if(!selected)throw new Error('Select a journal trade first');const intervals:SnapshotInterval[]=[];if(preferences.journal.snapshot5m)intervals.push('5');if(preferences.journal.snapshot1h)intervals.push('60');if(preferences.journal.snapshot1d)intervals.push('D');if(!intervals.length)throw new Error('Enable at least one Journal snapshot timeframe in Settings');const files=await createJournalChartSnapshots(selected,preferences,intervals);const prefixes=files.map(file=>file.name.split(selected.symbol.toUpperCase())[0]||'');for(const old of images.data||[]){const name=old.original_name||'';if(prefixes.some(prefix=>prefix&&name.startsWith(prefix)))await api(`/api/journal/images/${old.id}`,{method:'DELETE'});}for(const file of files)await uploadOne(selected.id,file,'entry');return files.length;},onSuccess:()=>{void qc.invalidateQueries({queryKey:['journal-images',selected?.id]});void qc.invalidateQueries({queryKey:['journal-page']});}});

  const accountNames=useMemo(()=>Object.fromEntries((config.data?.accounts||[]).map(a=>[a.id,a.name])),[config.data]);
  const metrics=q.data?.summary||{trades:0,winrate:0,net:0,avg:0,pf:0,avgWin:0,avgLoss:0};
  const breakdowns=q.data?.breakdowns||{style:[],account:[],side:[],point:[],setup:[]};
  const rows=q.data?.rows||[];
  const total=q.data?.total||0;
  const totalPages=q.data?.totalPages||1;
  const start=total?(q.data!.page-1)*q.data!.pageSize+1:0;
  const end=total?Math.min(total,start+rows.length-1):0;

  const setFilter=<K extends keyof FilterState>(key:K,value:FilterState[K])=>setFilters(prev=>({...prev,[key]:value,page:key==='page'?Number(value):1}));
  const resetFilters=()=>{setFilters({...defaultFilters,tab:filters.tab});localStorage.removeItem(FILTER_KEY);};
  useEffect(()=>{if(q.data&&q.data.page!==filters.page)setFilters(prev=>({...prev,page:q.data!.page}));},[q.data?.page]);
  useEffect(()=>{if(preferences.journal.rememberFilters){localStorage.setItem(FILTER_KEY,JSON.stringify({...filters,page:preferences.journal.rememberPage?filters.page:1}));}else localStorage.removeItem(FILTER_KEY);},[filters,preferences.journal.rememberFilters,preferences.journal.rememberPage]);
  useEffect(()=>{setFilters(prev=>({...prev,page:1}));},[preferences.journal.pageSize]);

  const patch=(values:any)=>{if(selected)update.mutate({id:selected.id,patch:values});};
  const tags=selected?parseTags(selected.tags_json):[];
  const acceptFiles=(files:File[])=>{const list=files.filter(Boolean);if(list.length)uploadImages.mutate({files:list,kind:shotKind});};
  useEffect(()=>{if(!selected)return;const onPaste=(event:ClipboardEvent)=>{const fromItems=Array.from(event.clipboardData?.items||[]).filter(item=>item.kind==='file'&&item.type.startsWith('image/')).map(item=>item.getAsFile()).filter((file):file is File=>Boolean(file));const pasted=fromItems.length?fromItems:Array.from(event.clipboardData?.files||[]).filter(f=>f.type.startsWith('image/'));if(!pasted.length)return;event.preventDefault();acceptFiles(pasted);};window.addEventListener('paste',onPaste);return()=>window.removeEventListener('paste',onPaste);},[selected,shotKind]);

  const sortLabel=(value:SortMode)=>value==='newest'?(language==='uk'?'Нові спочатку':language==='ru'?'Сначала новые':'Newest first'):value==='oldest'?(language==='uk'?'Старі спочатку':language==='ru'?'Сначала старые':'Oldest first'):value==='best_r'?(language==='uk'?'Найкращий R':language==='ru'?'Лучший R':'Best R'):value==='worst_r'?(language==='uk'?'Найгірший R':language==='ru'?'Худший R':'Worst R'):(language==='uk'?'Найбільший PnL':language==='ru'?'Максимальный PnL':'Highest PnL');

  return <div className="page journal-page">
    <div className="page-head"><div><h1>{t('Journal')}</h1><p>{language==='uk'?'Торговий щоденник, розбір і аналітика в R. Результат R заповнюється вручну.':language==='ru'?'Торговый дневник, разбор и аналитика в R. Результат R заполняется вручную.':'Trading diary, review and R-based analytics. Result R is entered manually.'}</p></div><button className="btn secondary" disabled={syncJournal.isPending} onClick={()=>syncJournal.mutate()}><RefreshCw size={14}/>{syncJournal.isPending?(language==='uk'?'Синхронізація…':language==='ru'?'Синхронизация…':'Syncing…'):'Sync Bybit'}</button></div>

    <div className="journal-tabs"><button className={filters.tab==='trades'?'tab active':'tab'} onClick={()=>setFilter('tab','trades')}>{t('Trades')}</button><button className={filters.tab==='analytics'?'tab active':'tab'} onClick={()=>setFilter('tab','analytics')}>{t('Analytics')}</button></div>
    <div className="card journal-filterbar">
      <select className="select" value={filters.account} onChange={e=>setFilter('account',Number(e.target.value))}><option value={0}>{t('All accounts')}</option>{config.data?.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>
      <input className="input" placeholder={t('Symbol')} value={filters.symbol} onChange={e=>setFilter('symbol',e.target.value.toUpperCase())}/>
      <select className="select" value={filters.side} onChange={e=>setFilter('side',e.target.value)}><option value="">Long + Short</option><option value="Buy">{t('Buy')}</option><option value="Sell">{t('Sell')}</option></select>
      <select className="select" value={filters.style} onChange={e=>setFilter('style',e.target.value)}><option value="">{language==='uk'?'Усі стилі':language==='ru'?'Все стили':'All styles'}</option><option value="1">Breakout</option><option value="2">LP</option><option value="3">Rebound</option><option value="0">{language==='uk'?'Без класифікації':language==='ru'?'Без классификации':'Unclassified'}</option></select>
      <select className="select" value={filters.status} onChange={e=>setFilter('status',e.target.value)}><option value="">{language==='uk'?'Усі статуси':language==='ru'?'Все статусы':'All status'}</option><option value="0">{t('New')}</option><option value="1">{t('Filled')}</option><option value="2">{t('Cancelled')}</option></select>
      <select className="select" value={filters.pointType} onChange={e=>setFilter('pointType',e.target.value)}><option value="">{language==='uk'?'Усі типи входу':language==='ru'?'Все типы входа':'All entry types'}</option>{Object.entries(pointTypeMap).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>
      <input className="input" type="date" value={filters.dateFrom} onChange={e=>setFilter('dateFrom',e.target.value)}/><input className="input" type="date" value={filters.dateTo} onChange={e=>setFilter('dateTo',e.target.value)}/>
      <select className="select" value={filters.sort} onChange={e=>setFilter('sort',e.target.value as SortMode)}>{(['newest','oldest','best_r','worst_r','highest_pnl'] as SortMode[]).map(v=><option key={v} value={v}>{sortLabel(v)}</option>)}</select>
      <button className="btn ghost" onClick={resetFilters}>{language==='uk'?'Скинути':language==='ru'?'Сбросить':'Reset'}</button>
    </div>

    <div className="journal-metrics">
      <div className="metric-card"><small>{t('Trades')}</small><strong>{metrics.trades}</strong></div><div className="metric-card"><small>{t('Winrate')}</small><strong>{metrics.winrate.toFixed(1)}%</strong></div><div className="metric-card"><small>{t('Net R')}</small><strong className={metrics.net>=0?'positive':'negative'}>{metrics.net>=0?'+':''}{metrics.net.toFixed(2)}R</strong></div><div className="metric-card"><small>{t('Profit Factor')}</small><strong>{metrics.pf===null?'∞':Number(metrics.pf).toFixed(2)}</strong></div><div className="metric-card"><small>{t('Expectancy')}</small><strong>{metrics.avg>=0?'+':''}{metrics.avg.toFixed(2)}R</strong></div>
    </div>

    {filters.tab==='trades'?<div className="card table-card journal-table-card"><table className="data-table journal-table"><thead><tr><th>{t('Date')}</th><th>{t('Exchange')}</th><th>{t('Account')}</th><th>{t('Symbol')}</th><th>{t('Side')}</th><th>{t('Entry')}</th><th>{t('SL')}</th><th>{t('TP / Exit')}</th><th>R</th><th>{t('Style')}</th><th>{t('Setup')}</th><th>{t('Status')}</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>setSelected(r)}><td>{r.occurred_at}</td><td>{String(r.exchange||'bybit').toUpperCase()}</td><td>{accountNames[r.account_id||0]||r.legacy_account||`Account ${r.account_id||'—'}`}</td><td><b>{r.symbol}</b>{Boolean(r.chart_path||Number(r.image_count||0)>0)&&<button className="journal-chart-icon" onClick={e=>{e.stopPropagation();setSelected(r);}} title={language==='uk'?'Відкрити скріншоти':language==='ru'?'Открыть скриншоты':'Open screenshots'}><ImageIcon size={13}/><span>{Number(r.image_count||0)+(r.chart_path?1:0)}</span></button>}</td><td className={r.side==='Buy'?'positive':'negative'}>{r.side?t(r.side):'—'}</td><td>{num(r.entry_price||0,8)}</td><td>{num(r.stop_loss||0,8)}</td><td>{num(r.exit_price||r.take_profit||0,8)}</td><td><span className={`rr-chip ${Number(r.rr)>0?'win':Number(r.rr)<0?'loss':''}`}>{Number(r.rr)>0?'+':''}{Number(r.rr||0)===0?'BE':`${Number(r.rr||0)}R`}</span></td><td>{styleMap[Number(r.style||0)]||'—'}</td><td>{r.setup||'—'}</td><td>{t(statusMap[Number(r.status||0)]||String(r.status??'—'))}</td><td>{r.note?'📝':''}</td></tr>)}</tbody></table>{!rows.length&&!q.isLoading&&<div className="empty">{t('No journal entries for the selected filters.')}</div>}
      <div className="journal-pagination"><div className="journal-page-summary">{language==='uk'?`Показано ${start}–${end} з ${total}`:language==='ru'?`Показано ${start}–${end} из ${total}`:`Showing ${start}–${end} of ${total}`}</div><div className="journal-page-controls"><button className="btn ghost" disabled={filters.page<=1} onClick={()=>setFilter('page',filters.page-1)}>←</button>{pageButtons(filters.page,totalPages).map(p=><button key={p} className={p===filters.page?'page-number active':'page-number'} onClick={()=>setFilter('page',p)}>{p}</button>)}<button className="btn ghost" disabled={filters.page>=totalPages} onClick={()=>setFilter('page',filters.page+1)}>→</button></div><div className="journal-page-size">{preferences.journal.pageSize} / page</div></div>
    </div>:
    <div className="analytics-grid"><section className="card analytics-card"><h3>{t('Performance')}</h3><div className="kv"><span>{t('Average winner')}</span><b>+{metrics.avgWin.toFixed(2)}R</b></div><div className="kv"><span>{t('Average loser')}</span><b>{metrics.avgLoss.toFixed(2)}R</b></div><div className="kv"><span>{t('Expectancy / trade')}</span><b>{metrics.avg>=0?'+':''}{metrics.avg.toFixed(2)}R</b></div><div className="kv"><span>{t('Net result')}</span><b className={metrics.net>=0?'positive':'negative'}>{metrics.net>=0?'+':''}{metrics.net.toFixed(2)}R</b></div></section>{([['By trading style',breakdowns.style],['By account',breakdowns.account],['Long / Short',breakdowns.side],['By entry type',breakdowns.point],['By setup',breakdowns.setup]] as const).map(([title,data])=><section key={title} className="card analytics-card analytics-wide"><h3>{t(title)}</h3><table className="data-table"><thead><tr><th>{t('Group')}</th><th>{t('Trades')}</th><th>{t('Winrate')}</th><th>{t('Net R')}</th><th>{t('Avg R')}</th></tr></thead><tbody>{data.map(x=>{const decided=x.wins+x.losses;return<tr key={x.name}><td>{x.name}</td><td>{x.trades}</td><td>{decided?(x.wins/decided*100).toFixed(1):'0.0'}%</td><td className={x.net>=0?'positive':'negative'}>{x.net>=0?'+':''}{x.net.toFixed(2)}R</td><td>{x.trades?(x.net/x.trades).toFixed(2):'0.00'}R</td></tr>})}</tbody></table></section>)}</div>}

    {selected&&<aside className="drawer journal-drawer"><div className="drawer-head"><div><h2>{selected.symbol} · {selected.side?t(selected.side):'—'}</h2><div className="muted">{selected.occurred_at} · {(selected.exchange||'bybit').toUpperCase()} · {accountNames[selected.account_id||0]||selected.legacy_account}</div></div><button className="icon-btn" onClick={()=>setSelected(null)}><X size={16}/></button></div>
      <div className="metric-grid journal-detail-metrics"><div className="metric"><small>{t('Entry')}</small><strong>{num(selected.entry_price||0,8)}</strong></div><div className="metric"><small>{t('Exit')}</small><strong>{selected.exit_price?num(selected.exit_price,8):'—'}</strong></div><div className="metric"><small>{t('SL')}</small><strong>{selected.stop_loss?num(selected.stop_loss,8):'—'}</strong></div><div className="metric"><small>{t('TP')}</small><strong>{selected.take_profit?num(selected.take_profit,8):'—'}</strong></div><div className="metric"><small>{t('Qty')}</small><strong>{selected.quantity?num(selected.quantity,8):'—'}</strong></div><div className="metric"><small>PnL</small><strong className={Number(selected.pnl||0)>=0?'positive':'negative'}>{selected.pnl===null?'—':money(selected.pnl)}</strong></div><div className="metric"><small>{t('Fee')}</small><strong>{selected.fees===null?'—':money(selected.fees)}</strong></div><div className="metric"><small>R</small><strong>{Number(selected.rr||0)===0?'BE':`${Number(selected.rr||0)>0?'+':''}${Number(selected.rr||0)}R`}</strong></div></div>
      <div className="drawer-section journal-trade-facts"><div className="kv"><span>{t('Account')}</span><b>{accountNames[selected.account_id||0]||selected.legacy_account||'—'}</b></div><div className="kv"><span>{t('Type')}</span><b>{selected.order_type||'—'}</b></div><div className="kv"><span>{t('Point type')}</span><b>{pointTypeMap[Number(selected.point_type||0)]||selected.point_type||'—'}</b></div><div className="kv"><span>{t('Status')}</span><b>{t(statusMap[Number(selected.status||0)]||String(selected.status??'—'))}</b></div><div className="kv"><span>{t('Price level')}</span><b>{selected.price_level?num(selected.price_level,8):'—'}</b></div></div>
      <div className="drawer-section"><div className="field-grid"><div className="field"><label>{t('Result R')}</label><select className="select" value={Number(selected.rr||0)} onChange={e=>patch({rr:Number(e.target.value)})}>{rrOptions.map(v=><option key={v} value={v}>{v===0?'BE / 0R':`${v>0?'+':''}${v}R`}</option>)}</select></div><div className="field"><label>{t('Style')}</label><select className="select" value={Number(selected.style||0)} onChange={e=>patch({style:Number(e.target.value)})}><option value={0}>—</option><option value={1}>Breakout</option><option value={2}>LP</option><option value={3}>Rebound</option></select></div></div><div className="field-grid"><div className="field"><label>{t('Status')}</label><select className="select" value={Number(selected.status||0)} onChange={e=>patch({status:Number(e.target.value)})}><option value={0}>{t('New')}</option><option value={1}>{t('Filled')}</option><option value={2}>{t('Cancelled')}</option></select></div><div className="field"><label>{t('Execution quality')}</label><select className="select" value={selected.execution_quality||''} onChange={e=>patch({executionQuality:e.target.value||null})}><option value="">—</option><option value="Excellent">{t('Excellent')}</option><option value="Good">{t('Good')}</option><option value="Average">{t('Average')}</option><option value="Poor">{t('Poor')}</option></select></div></div><div className="field"><label>{t('Setup')}</label><input className="input" value={selected.setup||''} placeholder={t('Daily mirror + rejection')} onChange={e=>setSelected({...selected,setup:e.target.value})} onBlur={e=>patch({setup:e.target.value||null})}/></div><div className="field"><label>{t('Tags · comma separated')}</label><input className="input" value={tags.join(', ')} placeholder={t('FOMO, daily level, high volume')} onChange={e=>setSelected({...selected,tags_json:JSON.stringify(e.target.value.split(',').map(x=>x.trim()).filter(Boolean))})} onBlur={e=>patch({tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></div><div className="field"><label>{t('Notes')}</label><textarea className="input journal-note" value={selected.note||''} placeholder={t('What was the idea? What went well? What should change next time?')} onChange={e=>setSelected({...selected,note:e.target.value})} onBlur={e=>patch({note:e.target.value||null})}/></div></div>
      <div className="drawer-section journal-images-section"><div className="journal-images-title"><div><h3>{t('Screenshots')}</h3><p>{language==='uk'?'Автознімки створюються без Print Screen і не змінюють поточний графік. Ручне завантаження та Ctrl+V залишаються.':language==='ru'?'Автоснимки создаются без Print Screen и не меняют текущий график. Ручная загрузка и Ctrl+V остаются.':'Auto snapshots are created without Print Screen and do not change the current chart. Manual upload and Ctrl+V still work.'}</p></div><select className="select journal-kind-select" value={shotKind} onChange={e=>setShotKind(e.target.value as JournalImage['kind'])}>{shotKinds.map(([value,label])=><option key={value} value={value}>{t(label)}</option>)}</select></div>
        <button className="btn secondary journal-auto-shot" disabled={generateSnapshots.isPending} onClick={()=>generateSnapshots.mutate()}><Camera size={15}/>{generateSnapshots.isPending?(language==='uk'?'Створення 5m / 1H / 1D…':language==='ru'?'Создание 5m / 1H / 1D…':'Creating 5m / 1H / 1D…'):(language==='uk'?'Створити графіки 5m / 1H / 1D':language==='ru'?'Создать графики 5m / 1H / 1D':'Create charts 5m / 1H / 1D')}</button>
        {generateSnapshots.error&&<div className="journal-upload-error">{generateSnapshots.error instanceof Error?generateSnapshots.error.message:'Snapshot failed'}</div>}
        <input ref={fileInput} className="journal-file-input" type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{acceptFiles(Array.from(e.target.files||[]));e.currentTarget.value='';}}/>
        <button type="button" className={`journal-dropzone ${dropActive?'active':''}`} onClick={()=>fileInput.current?.click()} onDragEnter={e=>{e.preventDefault();setDropActive(true);}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();if(e.currentTarget===e.target)setDropActive(false);}} onDrop={e=>{e.preventDefault();setDropActive(false);acceptFiles((Array.from(e.dataTransfer.files) as File[]).filter((f:File)=>f.type.startsWith('image/')));}}><UploadCloud size={20}/><span><b>{uploadImages.isPending?t('Uploading…'):t('Add screenshot')}</b><small>PNG / JPG / WEBP · up to 8 MB</small></span><span className="journal-paste-hint"><ClipboardPaste size={14}/> Ctrl+V</span></button>
        {uploadImages.error&&<div className="journal-upload-error">{uploadImages.error instanceof Error?uploadImages.error.message:t('Upload failed')}</div>}
        <div className="journal-image-grid">{selected.chart_path&&<article className="journal-image-card legacy"><button className="journal-image-preview" onClick={()=>setImage(`/charts/${selected.chart_path}`)}><img src={`/charts/${selected.chart_path}`} alt="Legacy trade chart"/></button><div className="journal-image-meta"><span>{t('Legacy')}</span><small>{t('Original screenshot')}</small></div></article>}{(images.data||[]).map(item=>{const auto=autoSnapshotLabel(item.original_name);return <article className="journal-image-card" key={item.id}><button className="journal-image-preview" onClick={()=>setImage(`/charts/${item.path}`)}><img src={`/charts/${item.path}`} alt={`${auto||kindLabel(item.kind)} screenshot`}/></button><div className="journal-image-meta"><span>{auto?`AUTO · ${auto}`:t(kindLabel(item.kind))}</span><small>{item.original_name||new Date(item.created_at).toLocaleString()}</small></div><button className="journal-image-delete" disabled={deleteImage.isPending} onClick={()=>{if(window.confirm(t('Delete this screenshot?')))deleteImage.mutate(item.id);}} title={t('Delete screenshot')}><Trash2 size={13}/></button></article>})}</div>
        {!selected.chart_path&&!images.isLoading&&!(images.data||[]).length&&<div className="journal-images-empty">{language==='uk'?'Скріншотів ще немає. Натисніть «Створити графіки 5m / 1H / 1D» або додайте свій.':language==='ru'?'Скриншотов пока нет. Нажмите «Создать графики 5m / 1H / 1D» или добавьте свой.':'No screenshots yet. Click “Create charts 5m / 1H / 1D” or add your own.'}</div>}
      </div>
    </aside>}
    {image&&<div className="image-modal" onClick={()=>setImage(null)}><img src={image}/></div>}
  </div>;
}
